mySite/mySite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mySite/polls/urls.py
from django.urls import path
from django.views.generic import  TemplateView
from . import views

app_name ='polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.viewlist, name='views_list'),
    path('detail/<int:question_id>', views.detailView, name='detail'),
    path('<int:question_id>/', views.vote, name='vote'),
]

mySite/polls/models.py
from django.db import models
from  django.db import  models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=500)
    time_pub = models.DateTimeField()

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    vote = models.IntegerField(default=0)

mySite/polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from  .models import Question

def index(request):
    myname="Lê Hùng"
    taiSan = ["Điện thoại", "máy tính", "ô tô"]
    context = {"name": myname, "taisan": taiSan}
    return render(request, "polls/index.html", context)

def viewlist(request):
    list_question = Question.objects.all()
    # list_question = get_object_or_404(Question, pk=1)
    context1 = {"dsquest": list_question}
    return render(request, "polls/question_list.html", context1)


def detailView(request, question_id):
    q = Question.objects.get(pk=question_id)
    return render(request, "polls/detail_question.html", {"qs": q})

def vote(request, question_id):
    q = Question.objects.get(pk=question_id)
    try:
        dulieu = request.POST["choice"]
        c = q.choice_set.get(pk=dulieu)
    except:
        HttpResponse("Lỗi không có choice")
    c.vote = int(c.vote) + 1
    c.save()
    return render(request, "polls/result.html", {"q": q})

mySite/polls/templates/polls/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        .header{
            padding: 30px;
            background-color: #ccc;
            color: #fff;
        }
        .menu{
            background-color: #cccccc;
            color: #fff;
        }
        .menu ul li{
            float: left;
            padding: 10px;
            list-style: none;
        }
        .menu::after{
            clear: both;
            display: table;
            content: "";
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>My website</h1>
    </div>
    <div class="menu">
        <ul>
            <li>link1</li>
            <li>link2</li>
            <li>link3</li>
            <li>link4</li>
        </ul>
    </div>
    <div class="content">
        {% block content1%}

        {%endblock%}
       {% block question_list %}

        {%endblock%}
        {% block question_result %}

        {%endblock%}
    </div>
</body>
</html>

mySite/polls/templates/polls/detail_question.html
{% extends 'polls/base.html'%}

    {% block question_list %}
        {% if qs %}
        <h3 style="margin-left: 50px">{{qs.question_text}}</h3>
        <form action="{% url 'polls:vote' qs.id %}" method="post">
            {% csrf_token %}
            <ul>
                {% for item in qs.choice_set.all %}
                    <li style="list-style: none">
                        <input type="radio" value="{{item.id}}" name="choice">
                        {{item.choice_text}}
                    </li>
                {% endfor %}
                <p><input type="submit" value="gửi"></p>
            </ul>
        </form>
        {% endif %}
    {%endblock%}

mySite/polls/templates/polls/index.html
{% extends 'polls/base.html'%}

    {% block content1 %}
     <h1>Đây là templade</h1>
    <p> Chào các bạn mình là {{ name}}</p>
    <h2>Tài sản tôi gồm:</h2>
    <ul>
        {% for item in taisan %}
            {% if item != 'máy tính' %}
                <li>{{item}}</li>
            {% endif%}

        {% endfor%}
    </ul>
    {%endblock%}

mySite/polls/templates/polls/question_list.html
{% extends 'polls/base.html'%}

    {% block question_list %}
        {% if dsquest %}
            {% for item in dsquest %}
                <a href="{% url 'polls:detail' item.id %}" style="text-decoration: none">
                    <p>
                        {{item.question_text}}
                    </p>
                </a>
            {% endfor %}
        {% else %}
            <h3 style="color: red;">Không có dữ liệu câu hỏi !!!</h3>
        {% endif %}
    {%endblock%}

mySite/polls/templates/polls/result.html
{% extends 'polls/base.html'%}

    {% block question_result %}
        {% if q %}
            <h3>{{ q.question_text }}</h3>
            <p>kết quả bình chọn là:</p>
            {% for item in q.choice_set.all %}
                <p>{{ item.choice_text }} : <span style="color: #ff5833">{{ item.vote}}</span></p>
            {% endfor %}
            <a href="{% url 'polls:views_list' %}">next</a>
        {% endif %}
    {%endblock%}